image: registry.yougov.net/yougov/base

test:
  script: tox

release:
  stage: deploy
  before_script:
  - python3.6 -m pip install wheel devpi-client
  - python3.6 -m pip install -i https://devpi.yougov.net/root/yg/ -e .[docs]
  script:
  - python3.6 -m devpi use https://devpi-master.yougov.net/root/yg/
  - python3.6 -m devpi login $DEVPI_USERNAME --password $DEVPI_PASSWORD
  # workaround for devpi #395
  - ln -s $(which python3.6) /usr/local/bin/python
  - python3.6 -m devpi upload --formats bdist_wheel,sdist --with-docs
  only:
  - tags
